### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by hutchyx** [bgottsch/homebridge-isy-hub#1]
Installed HomeBridge today.
Installed homebridge-isy plugin

modified config adding this to the platforms collection:
         {
            "platform": "ISY-994i",
            "name": "ISY-994i",
            "username": "admin",
            "password": "<my_password_removed>",
            "host": "10.0.0.160",
            "refresh_interval": 30000,
            "scenes": [
                {
                    "name": "Hallway Lamp",
                    "id": 39793,
                    "type": "light_scene"
                },
                {
                    "name": "Hallway Fan",
                    "id": 26451,
                    "type": "light_scene"
                }
            ]
        }

HomeBridge restarts but errors and continues restarting
TypeError: Cannot read property 'forEach' of undefined
    at ISYPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-isy/lib/platform.js:107:25)
    at API.emit (events.js:310:20)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by bgottsch** [comment]
Hey,

Sorry for that bug, I've been finalizing this plugin during this weekend but released a version with som minor issues still. I'll update to a stable version this week, probably until Tueday.

For the mean time, your error can simply be fixed by adding `"devices": [],` to the config, as shown below. I have to update the read me part of this project.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file.",
    "platforms": [
        {
            "platform": "ISY-994i",
            "name": "ISY-994i",
            "username": "<USERNAME>",
            "password": "<PASSWORD>",
            "host": "<IP-ADDRESS>",
            "refresh_interval": 30000,
            "devices": [],
            "scenes": [
                {
                    "name": "Curtain Open-Close",
                    "id": 9040,
                    "type": "light_scene"
                }
            ]
        }
    ],
    "accessories": []
}
```

I'm currently working on adding individual devices support, as well as a new type of scene for Keypads, based on Stateless Switches.

Let me know it you have any other issues.

**Comment by bgottsch** [comment]
@hutchyx take a look at the updated version of the project. If just uploaded it to github/npm. Version should be 0.0.4

There are still many things to do, such as the README, or stateless switches. But it's a working version for now, if your interested. Take a look at the file `config.example.json` to see how to configure it.

Best regards
